include(${CMAKE_CURRENT_LIST_DIR}/dep_versions.cmake)

if(${CMSB_PROJECTS}_HAS_CUDA)
    set(CUTLASS_GPU_ARCH "-DCUTLASS_NVCC_ARCHS=${GPU_ARCH}")
elseif(${CMSB_PROJECTS}_HAS_HIP)
    set(CUTLASS_GPU_ARCH "-DCUTLASS_NVCC_ARCHS=${GPU_ARCH}")
endif()

if(ENABLE_OFFLINE_BUILD)
ExternalProject_Add(CUTLASS_External
    URL ${DEPS_LOCAL_PATH}/cutlass
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} ${CUTLASS_GPU_ARCH} -DCUTLASS_ENABLE_HEADERS_ONLY=ON
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
else()
ExternalProject_Add(CUTLASS_External
    GIT_REPOSITORY https://github.com/NVIDIA/cutlass
    GIT_TAG ${CUTLASS_GIT_TAG}
    UPDATE_DISCONNECTED 1
    CMAKE_ARGS ${DEPENDENCY_CMAKE_OPTIONS} ${CUTLASS_GPU_ARCH} -DCUTLASS_ENABLE_HEADERS_ONLY=ON
    INSTALL_COMMAND ${CMAKE_MAKE_PROGRAM} install DESTDIR=${STAGE_DIR}
    CMAKE_CACHE_ARGS ${CORE_CMAKE_LISTS}
                     ${CORE_CMAKE_STRINGS}
)
endif()

